### ISSUE TITLE
Just wanted to make sure you saw my `rewrite` branch

### ISSUE THREAD

**Issue by JJTech0130** [Site-Automation/leap_hub#1]
I just wanted to make sure that you are using `rewrite` branch it contains much cleaner code, and it implements some of the things you re-implemented. If you already saw it, sorry 😅.

**Comment by JJTech0130** [comment]
Also, just wanted to ask if you have the LEAP documentation, and if so, where did you get it? Do you know where to find new versions? I only have 1.120 and 3.0 (040458a_Preliminary), which are internal drafts and my own experimentation.

**Comment by aleccmedina-ee** [comment]
I do have the documentation and I have saw your branch. I need to check if I am allowed to share it, if so ill add it to the repo.

**Comment by JJTech0130** [comment]
Ok thanks. Closing the issue then.
